'use strict';
const $=id=>document.getElementById(id),cfg=window.ACCESS_CONFIG;
let session='',expiry=0,working=false;
function element(tag,text,cls){const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e}
function feedback(text){$('adminFeedback').textContent=text}
function ready(){if(!cfg?.supabaseUrl||!cfg?.publishableKey)throw new Error('Erişim hizmeti henüz yapılandırılmadı.')}
async function api(body){ready();if(Date.now()>=expiry){logout();throw new Error('Oturum süresi doldu. Yeniden giriş yapın.')}const r=await fetch(cfg.supabaseUrl+'/functions/v1/thaimcp-access',{method:'POST',headers:{apikey:cfg.publishableKey,Authorization:'Bearer '+session,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'İşlem tamamlanamadı.');return d}
function logout(){session='';expiry=0;$('management').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('keyList').replaceChildren();hideKey()}
function hideKey(){$('newKey').textContent='';$('oneTime').hidden=true}
function reveal(key){$('newKey').textContent=key;$('oneTime').hidden=false;$('oneTime').scrollIntoView({behavior:'smooth'})}
async function list(){const d=await api({action:'list'});$('keyList').replaceChildren();for(const k of d.keys){const c=element('article','','source-card');c.append(element('h3',k.label),element('p',k.key_prefix+'••••••••• · '+(k.revoked_at?'İptal edildi':k.active?'Aktif':'Pasif')),element('p','Kullanım: '+k.usage_count),element('p','Oluşturulma: '+new Date(k.created_at).toLocaleString('tr-TR')),element('p','Son kullanım: '+(k.last_used_at?new Date(k.last_used_at).toLocaleString('tr-TR'):'Henüz kullanılmadı')),element('p','Süre sonu: '+(k.expires_at?new Date(k.expires_at).toLocaleString('tr-TR'):'Süresiz')));for(const [label,action] of [[k.active?'Pasif yap':'Aktif yap','toggle'],['İptal et','revoke'],['Yeni anahtar oluştur','rotate']]){const b=element('button',label,'secondary');b.disabled=Boolean(k.revoked_at)&&action!=='rotate';b.onclick=()=>operate(async()=>{hideKey();const d=await api({action,id:k.id,label:k.label,active:!k.active,expires_at:k.expires_at&&new Date(k.expires_at)>new Date()?k.expires_at:null});if(d.key)reveal(d.key);await list();feedback('İşlem tamamlandı.')});c.append(b)}$('keyList').append(c)}if(!d.keys.length)$('keyList').append(element('p','Henüz erişim anahtarı oluşturulmadı.'))}
async function operate(fn){if(working)return;working=true;try{await fn()}catch(e){feedback(e.message)}finally{working=false}}
$('login').onsubmit=e=>{e.preventDefault();operate(async()=>{ready();feedback('Oturum doğrulanıyor…');const password=$('password').value;$('password').value='';const r=await fetch(cfg.supabaseUrl+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok)throw new Error('E-posta veya şifre geçersiz.');session=d.access_token;expiry=Date.now()+d.expires_in*1000;try{await list()}catch(e){logout();throw e}$('management').hidden=false;$('login').hidden=true;$('logout').hidden=false;feedback('Yönetici oturumu doğrulandı.')})};
$('create').onsubmit=e=>{e.preventDefault();operate(async()=>{hideKey();const d=await api({action:'create',label:$('label').value.trim(),expires_at:$('expiry').value?new Date($('expiry').value).toISOString():null});reveal(d.key);await list();feedback('Anahtar oluşturuldu. Şimdi kopyalayın.')})};
$('refresh').onclick=()=>operate(list);$('logout').onclick=logout;$('dismissKey').onclick=hideKey;$('copyKey').onclick=()=>operate(async()=>{await navigator.clipboard.writeText($('newKey').textContent);feedback('Anahtar kopyalandı.')});
