'use strict';
const $=id=>document.getElementById(id);
const local=['127.0.0.1','localhost'].includes(location.hostname);
const base=local?'':'http://127.0.0.1:8765';
let token='',mode='research',last=null,page=1,busy=false,accessKey='',keyValid=false;
const accessConfig=window.ACCESS_CONFIG;
$('submit').disabled=true;
$('accessGate').showModal();
$('gateClose').onclick=()=>$('accessGate').close();
$('accessForm').onsubmit=async e=>{e.preventDefault();const key=$('accessKey').value.trim();$('accessKey').value='';$('keyFeedback').textContent='Anahtar doğrulanıyor…';try{if(!accessConfig?.supabaseUrl||!accessConfig.publishableKey)throw new Error('Erişim hizmeti henüz yapılandırılmadı.');const r=await fetch(accessConfig.supabaseUrl+'/functions/v1/thaimcp-access',{method:'POST',headers:{apikey:accessConfig.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({action:'verify',key}),signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok||d.valid!==true)throw new Error(r.status===429?'Çok fazla deneme. Bir dakika bekleyin.':'Erişim anahtarı geçersiz.');accessKey=key;keyValid=true;$('submit').disabled=false;$('keyFeedback').textContent='Anahtar geçerli.';$('accessGate').close();$('feedback').replaceChildren(node('p','Anahtar geçerli. Yerel Qwen bu bilgisayarda çalışır.'));}catch(e){accessKey='';keyValid=false;$('submit').disabled=true;$('keyFeedback').textContent=e.message;}};
$('accessGate').addEventListener('cancel',()=>{if(!keyValid)$('feedback').replaceChildren(node('p','Sistemi kullanmak için erişim anahtarı gereklidir.'))});
if(local){const script=document.createElement('script');script.src='/session.js';script.onload=()=>{token=window.LOCAL_TOKEN||'';delete window.LOCAL_TOKEN};document.head.append(script)}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
async function status(){try{const r=await fetch(base+'/api/status',{signal:AbortSignal.timeout(8000)});const d=await r.json();$('status').textContent=d.ready?'Yerel AI bağlı · Qwen 1.7B':'Yerel AI hazır değil';}catch{$('status').textContent=local?'Yerel AI bağlantısı kapalı':'Yerel bağlantı için ağ izni gerekli olabilir'}}
status();
$('connection').onclick=()=>{$('settings').showModal()};
const accessButton=node('button','Erişim anahtarı','nav');accessButton.onclick=()=>$('accessGate').showModal();document.querySelector('nav').append(accessButton);const adminLink=node('a','Yönetici girişi','nav');adminLink.href='admin.html';document.querySelector('nav').append(adminLink);
$('save').onclick=e=>{e.preventDefault();token=$('localToken').value.trim();$('localToken').value='';$('settings').close();status()};
$('new').onclick=()=>{if(busy)return;mode='research';last=null;page=1;$('heading').replaceChildren(node('span','Hukuki sorununuzu kaynaklarıyla araştırın.'));$('question').value='';$('result').hidden=true;$('feedback').replaceChildren();$('petition').classList.remove('active');$('new').classList.add('active');$('question').focus()};
$('petition').onclick=()=>{if(busy)return;mode='petition';$('heading').textContent='Dilekçenizin araştırma taslağını hazırlayın.';$('petition').classList.add('active');$('new').classList.remove('active');$('question').focus()};
$('sourcesNav').onclick=()=>{if(last)$('sources').scrollIntoView({behavior:'smooth'});else $('feedback').replaceChildren(node('p','Kaynakları görmek için önce araştırma yapın.'))};
function card(s){const c=node('article','','source-card');c.append(node('h4',s.title));c.append(node('p',s.verified?'Kaynak metni alındı · Alaka '+s.score:'Doğrulanmış metin bulunamadı'));const md=s.metadata||{};const fields=[['Mahkeme / daire',md.mahkeme||md.birim],['Esas',md.esas_no||md.basvuru_no],['Karar',md.karar_no],['Tarih',md.karar_tarihi],['Kanun',md.kanun_no],['Madde',md.madde_no]];for(const [label,value] of fields)if(value)c.append(node('p',label+': '+value));const claim=last?.claims?.find(q=>q.kaynak_id===s.id);const passage=claim?.alinti||md.ilgili_pasaj;if(passage)c.append(node('blockquote',passage,'quote'));const a=node('a','Resmî kaynağı aç ↗');try{const u=new URL(s.url);if(u.protocol==='https:'&&['emsal.uyap.gov.tr','karararama.danistay.gov.tr','kararlarbilgibankasi.anayasa.gov.tr','mevzuat.adalet.gov.tr','mevzuat.gov.tr','www.mevzuat.gov.tr','bedesten.adalet.gov.tr'].includes(u.hostname)){a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';c.append(a)}}catch{}const scores=document.createElement('details');scores.append(node('summary','Sıralama gerekçeleri'));for(const [k,v] of Object.entries(md.alaka_bilesenleri||{}))if(v>0)scores.append(node('p',k.replaceAll('_',' ')+': '+v));c.append(scores);const details=document.createElement('details');details.append(node('summary','Kaynak tam metni'));details.append(node('pre',s.text));c.append(details);return c}
function render(d){last=d;$('result').hidden=false;$('analysis').replaceChildren(...[d.analysis.dava_turu,d.analysis.hukuki_konu,d.analysis.alt_konu].filter(Boolean).map(x=>node('span',x,'chip')));$('answer').textContent=d.petition||d.answer;$('answerLabel').textContent=d.petition?'Dilekçe araştırma taslağı':'Kaynaklı araştırma taslağı';$('laws').replaceChildren(...d.sources.filter(s=>s.kind==='mevzuat').map(card));$('cases').replaceChildren(...d.sources.filter(s=>s.kind==='ictihat').map(card));for(const id of ['laws','cases'])if(!$(id).childNodes.length)$(id).append(node('p','Bu araştırmada doğrulanmış kaynak elde edilemedi.'));$('errors').replaceChildren(...d.errors.map(e=>node('p',e.asama+': '+e.hata,'error')));$('conflicts').replaceChildren(...d.conflicts.map(c=>node('p',c.durum+'\n'+c.kaynaklar.map(s=>'['+s.kaynak_id+'] '+s.alinti).join('\n'),'error')));$('download').hidden=!d.petition;$('feedback').replaceChildren(node('p',d.sources.length+' doğrulanmış kaynak · '+(d.metrics?.total_seconds||'—')+' saniye. '+d.privacy));}
async function run(limit=10){if(busy)return;if(!keyValid){$('accessGate').showModal();return}if(!token){$('settings').showModal();return}const text=$('question').value.trim();if(text.length<15){$('feedback').replaceChildren(node('p','Soruyu en az 15 karakterle yazın.'));return}busy=true;$('submit').disabled=true;$('more').disabled=true;$('feedback').replaceChildren(node('p','Erişim anahtarı doğrulanıyor…','loading'));try{const r=await fetch(base+'/api/research/stream',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':token,'X-Access-Key':accessKey},body:JSON.stringify({text,limit,page,mode,court:$('court').value}),signal:AbortSignal.timeout(180000)});if(!r.ok){const d=await r.json();if(r.status===401){accessKey='';keyValid=false;$('accessGate').showModal()}throw new Error(d.error||'Araştırma tamamlanamadı')}const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',completed=false;while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});let nl;while((nl=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,nl);buffer=buffer.slice(nl+1);if(!line)continue;const e=JSON.parse(line);if(e.type==='progress')$('feedback').replaceChildren(node('p',e.data.message,'loading'));else if(e.type==='result'){render(e.data);completed=true}else if(e.type==='error')throw new Error(e.data.error)}if(done)break}if(!completed)throw new Error('Bağlantı sonuç alınmadan kapandı.')}catch(e){$('feedback').replaceChildren(node('p',e.message+'. Yerel uygulamayı ve bağlantı ayarlarını kontrol edin.','error'))}finally{busy=false;$('submit').disabled=!keyValid;$('more').disabled=false}}
$('researchForm').onsubmit=e=>{e.preventDefault();page=1;run()};
$('more').onclick=()=>{if(page<10){page++;run(20)}};
$('narrow').onclick=()=>{$('question').focus();$('question').scrollIntoView({behavior:'smooth'});$('feedback').replaceChildren(node('p','Sorunuza daire, dönem veya tartışmalı hukuki koşulu ekleyip yeniden araştırın.'))};
$('download').onclick=()=>{if(!last?.petition)return;const a=document.createElement('a');const url=URL.createObjectURL(new Blob([last.petition],{type:'text/plain;charset=utf-8'}));a.href=url;a.download='dilekce-arastirma-taslagi.txt';a.click();URL.revokeObjectURL(url)};
