'use strict';
const $=id=>document.getElementById(id);
const local=['127.0.0.1','localhost'].includes(location.hostname);
const base=local?'':'http://127.0.0.1:8765';
let token='',mode='research',last=null,page=1,busy=false;
if(local){const script=document.createElement('script');script.src='/session.js';script.onload=()=>{token=window.LOCAL_TOKEN||'';delete window.LOCAL_TOKEN};document.head.append(script)}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
async function status(){try{const r=await fetch(base+'/api/status',{signal:AbortSignal.timeout(8000)});const d=await r.json();$('status').textContent=d.ready?'Yerel AI bağlı · Qwen 1.7B':'Yerel AI hazır değil';}catch{$('status').textContent=local?'Yerel AI bağlantısı kapalı':'Yerel bağlantı için ağ izni gerekli olabilir'}}
status();
$('connection').onclick=()=>{$('settings').showModal()};
$('save').onclick=e=>{e.preventDefault();token=$('localToken').value.trim();$('localToken').value='';$('settings').close();status()};
$('new').onclick=()=>{if(busy)return;mode='research';last=null;page=1;$('heading').replaceChildren(node('span','Hukuki sorununuzu kaynaklarıyla araştırın.'));$('question').value='';$('result').hidden=true;$('feedback').replaceChildren();$('petition').classList.remove('active');$('new').classList.add('active');$('question').focus()};
$('petition').onclick=()=>{if(busy)return;mode='petition';$('heading').textContent='Dilekçenizin araştırma taslağını hazırlayın.';$('petition').classList.add('active');$('new').classList.remove('active');$('question').focus()};
$('sourcesNav').onclick=()=>{if(last)$('sources').scrollIntoView({behavior:'smooth'});else $('feedback').replaceChildren(node('p','Kaynakları görmek için önce araştırma yapın.'))};
function card(s){const c=node('article','','source-card');c.append(node('h4',s.title));c.append(node('p',s.verified?'Kaynak metni alındı · Alaka '+s.score:'Doğrulanmış metin bulunamadı'));c.append(node('p',s.id));const a=node('a','Resmî kaynağı aç ↗');try{const u=new URL(s.url);if(u.protocol==='https:'&&['emsal.uyap.gov.tr','karararama.danistay.gov.tr','kararlarbilgibankasi.anayasa.gov.tr','mevzuat.adalet.gov.tr','mevzuat.gov.tr','www.mevzuat.gov.tr','bedesten.adalet.gov.tr'].includes(u.hostname)){a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';c.append(a)}}catch{}const details=document.createElement('details');details.append(node('summary','Metin ve karar detayları'));const md=Object.fromEntries(Object.entries(s.metadata).filter(([k])=>k!=='alaka_bilesenleri'));details.append(node('pre',JSON.stringify(md,null,2)+'\n\n'+s.text));c.append(details);return c}
function render(d){last=d;$('result').hidden=false;$('analysis').replaceChildren(...[d.analysis.dava_turu,d.analysis.hukuki_konu,d.analysis.alt_konu].filter(Boolean).map(x=>node('span',x,'chip')));$('answer').textContent=d.petition||d.answer;$('answerLabel').textContent=d.petition?'Dilekçe araştırma taslağı':'Kaynaklı araştırma taslağı';$('laws').replaceChildren(...d.sources.filter(s=>s.kind==='mevzuat').map(card));$('cases').replaceChildren(...d.sources.filter(s=>s.kind==='ictihat').map(card));for(const id of ['laws','cases'])if(!$(id).childNodes.length)$(id).append(node('p','Bu araştırmada doğrulanmış kaynak elde edilemedi.'));$('errors').replaceChildren(...d.errors.map(e=>node('p',e.asama+': '+e.hata,'error')));$('conflicts').replaceChildren(...d.conflicts.map(c=>node('p',c.durum+'\n'+c.kaynaklar.map(s=>'['+s.kaynak_id+'] '+s.alinti).join('\n'),'error')));$('download').hidden=!d.petition;$('feedback').replaceChildren(node('p',d.sources.length+' kaynak incelendi. '+d.privacy));}
async function run(limit=10){if(busy)return;if(!token){$('settings').showModal();return}const text=$('question').value.trim();if(text.length<15){$('feedback').replaceChildren(node('p','Soruyu en az 15 karakterle yazın.'));return}busy=true;$('submit').disabled=true;$('more').disabled=true;$('feedback').replaceChildren(node('p','Hukuki problem analiz ediliyor; mevzuat ve içtihat kaynakları araştırılıyor. Bu işlem birkaç dakika sürebilir.','loading'));try{const r=await fetch(base+'/api/research',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':token},body:JSON.stringify({text,limit,page,mode,court:$('court').value})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Araştırma tamamlanamadı');render(d)}catch(e){$('feedback').replaceChildren(node('p',e.message+'. Yerel uygulamayı ve bağlantı ayarlarını kontrol edin.','error'))}finally{busy=false;$('submit').disabled=false;$('more').disabled=false}}
$('researchForm').onsubmit=e=>{e.preventDefault();page=1;run()};
$('more').onclick=()=>{if(page<10){page++;run(20)}};
$('narrow').onclick=()=>{$('question').focus();$('question').scrollIntoView({behavior:'smooth'});$('feedback').replaceChildren(node('p','Sorunuza daire, dönem veya tartışmalı hukuki koşulu ekleyip yeniden araştırın.'))};
$('download').onclick=()=>{if(!last?.petition)return;const a=document.createElement('a');const url=URL.createObjectURL(new Blob([last.petition],{type:'text/plain;charset=utf-8'}));a.href=url;a.download='dilekce-arastirma-taslagi.txt';a.click();URL.revokeObjectURL(url)};
